# Example neuron-rtd dockerfile.

FROM ubuntu:18.04

LABEL maintainer="Mahendra Bairagi @bairagi"

# Install dependencies

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y && apt-get install -y apt-utils

RUN apt-get install -y wget \ 
&& apt-get install -y gnupg2 \
&& apt-get install -y ca-certificates 

RUN echo "deb https://apt.repos.neuron.amazonaws.com bionic main" | tee "/etc/apt/sources.list.d/neuron.list"

RUN wget -qO - https://apt.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB | apt-key add - 

RUN apt-get update \
&& apt-get install -y linux-headers-$(uname -r)

RUN sudo apt-get install -y aws-neuron-dkms \
&& sudo apt-get install -y aws-neuron-runtime-base \
&& sudo apt-get install -y aws-neuron-runtime \
&& sudo apt-get install -y aws-neuron-tools


RUN apt-get install -y \
    tar \
    gzip \
    ca-certificates \
    procps \
    net-tools \
    vim \
    libgomp1 \
    jq \
    python3 \
    python3-dev \
    python3-pip \
    build-essential \
    git 

RUN pip3 install --extra-index-url https://pip.repos.neuron.amazonaws.com/ neuron-cc torch-neuron

RUN pip3 install --upgrade --force-reinstall --no-cache-dir \ 
    transformers \
    captum 

# Installing opnejdk11
RUN apt-get install -y openjdk-11-jdk

RUN pip3 install --no-cache-dir \
    torchserve==0.3.0 torch-model-archiver==0.3.0 protobuf

ENV PYTHONUNBUFFERED=TRUE
ENV PYTHONDONTWRITEBYTECODE=TRUE

# Set up the model in the image
COPY ./model_store /opt/model_store
COPY ./config.properties /opt/config.properties 
COPY ./dockerd-entrypoint.sh /opt/bin/dockerd-entrypoint.sh
RUN chmod +x /opt/bin/dockerd-entrypoint.sh
ENV PATH="/opt/bin/:/opt/aws/neuron/bin:${PATH}"

WORKDIR /opt

EXPOSE 8443

ENTRYPOINT ["/opt/bin/dockerd-entrypoint.sh"]

CMD ["serve"]